import { INITIAL_RESEARCH } from './research';
import type {
  Building,
  CityPlacements,
  GameState,
  Quest,
  ResourceBag,
  RocketModule,
} from './types';

export const RESOURCE_LABELS: Record<keyof ResourceBag, string> = {
  credits: 'Credits',
  wood: 'Holz',
  metal: 'Metall',
  energy: 'Energie',
  crystal: 'Kristall',
  titan: 'Titan',
  silicon: 'Silizium',
  alien: 'Alien-Partikel',
};

export const RESOURCE_ICONS: Record<keyof ResourceBag, string> = {
  credits: 'C',
  wood: 'H',
  metal: 'M',
  energy: 'E',
  crystal: 'K',
  titan: 'T',
  silicon: 'S',
  alien: 'A',
};

export const ZERO_RESOURCES: ResourceBag = {
  credits: 0,
  wood: 0,
  metal: 0,
  energy: 0,
  crystal: 0,
  titan: 0,
  silicon: 0,
  alien: 0,
};

export const INITIAL_MODULES: RocketModule[] = [
  { key: 'engine', name: 'Triebwerk', level: 1, icon: 'engine' },
  { key: 'collector', name: 'Sammelmodul', level: 1, icon: 'collector' },
  { key: 'cargo', name: 'Frachtraum', level: 1, icon: 'cargo' },
  { key: 'laser', name: 'Bergbau-Laser', level: 1, icon: 'laser' },
  { key: 'energyCore', name: 'Energiemodul', level: 1, icon: 'energy' },
  { key: 'weapon', name: 'Waffenmodul', level: 1, icon: 'weapon' },
  { key: 'shield', name: 'Schildmodul', level: 1, icon: 'shield' },
];

export const INITIAL_BUILDINGS: Building[] = [
  {
    key: 'townhall',
    name: 'Rathaus',
    level: 0,
    icon: 'capitol',
    production: { credits: 18 },
  },
  {
    key: 'sawmill',
    name: 'Saegewerk',
    level: 0,
    icon: 'wood',
    production: { wood: 12 },
  },
  {
    key: 'quarry',
    name: 'Steinbruch',
    level: 0,
    icon: 'stone',
    production: { metal: 8 },
  },
  {
    key: 'forge',
    name: 'Schmiede',
    level: 0,
    icon: 'forge',
    production: { metal: 6, credits: 4 },
  },
  {
    key: 'research',
    name: 'Forschungszentrum',
    level: 0,
    icon: 'dome',
    production: { crystal: 0.4 },
  },
  {
    key: 'spaceport',
    name: 'Raumfahrtzentrum',
    level: 0,
    icon: 'rocket',
    production: {},
  },
  {
    key: 'power',
    name: 'Energieanlage',
    level: 0,
    icon: 'power',
    production: { energy: 100 },
  },
  {
    key: 'warehouse',
    name: 'Lager',
    level: 0,
    icon: 'warehouse',
    production: { credits: 3 },
  },
];

export const INITIAL_CITY_PLACEMENTS: CityPlacements = {
  townhall: 'slot-06',
  sawmill: 'slot-05',
  quarry: 'slot-07',
  forge: 'slot-02',
  research: 'slot-08',
  spaceport: 'slot-01',
  power: 'slot-04',
  warehouse: 'slot-03',
};

export const QUEST_CHAIN: Quest[] = [
  {
    title: 'Zerstoere deinen ersten grossen Asteroiden',
    hint: 'Klicke einen grossen Asteroiden im Weltraum, bis seine HP auf 0 fallen.',
    goal: 'destroy',
    current: 0,
    target: 1,
    reward: { credits: 900, metal: 240 },
    done: false,
  },
  {
    title: 'Verbessere den Bergbau-Laser auf Stufe 2',
    hint: 'Der Laser macht jeden Klick wertvoller.',
    goal: 'module',
    targetKey: 'laser',
    current: 1,
    target: 2,
    reward: { credits: 1200, metal: 180 },
    done: false,
  },
  {
    title: 'Sammle 200 Metall fuer die Werft',
    hint: 'Meteoriten liefern die Baustoffe fuer deine Basis.',
    goal: 'collect',
    targetKey: 'metal',
    current: 0,
    target: 200,
    reward: { crystal: 90, credits: 1400 },
    done: false,
  },
  {
    title: 'Baue das Forschungszentrum auf Stufe 2',
    hint: 'Forschung bereitet neue Sektoren und spaetere Technologien vor.',
    goal: 'building',
    targetKey: 'research',
    current: 1,
    target: 2,
    reward: { silicon: 120, crystal: 140 },
    done: false,
  },
  {
    title: 'Bereite den Raketenneubau vor',
    hint: 'Erforsche die neue Rakete und baue sie spaeter im Raumfahrtzentrum.',
    goal: 'building',
    targetKey: 'spaceport',
    current: 1,
    target: 3,
    reward: { alien: 40, credits: 2200 },
    done: false,
  },
];

export const INITIAL_STATE: GameState = {
  view: 'space',
  level: 7,
  questIndex: 0,
  resources: {
    credits: 2500,
    wood: 2500,
    metal: 2500,
    energy: 120,
    crystal: 1280,
    titan: 420,
    silicon: 180,
    alien: 45,
  },
  currentSector: 'alpha',
  unlockedSectors: ['alpha'],
  collectedTotals: {},
  destroyedAsteroids: 0,
  research: INITIAL_RESEARCH,
  modules: INITIAL_MODULES,
  buildings: INITIAL_BUILDINGS,
  cityPlacements: INITIAL_CITY_PLACEMENTS,
  rocket: {
    x: 33,
    y: 56,
    targetX: 54,
    targetY: 45,
    angle: 36,
    status: 'collecting',
    fuel: 100,
    fuelMax: 100,
    refuelTimer: 0,
    refuelDuration: 180,
    returnTimer: 0,
    returnDuration: 120,
    grabTimer: 0,
    grabDuration: 1.4,
    cargo: {},
  },
  asteroids: [
    {
      id: 1,
      type: 'iron',
      x: 72,
      y: 31,
      hp: 1800,
      maxHp: 1800,
      resource: 'metal',
    },
    {
      id: 2,
      type: 'titan',
      x: 84,
      y: 57,
      hp: 2400,
      maxHp: 2400,
      resource: 'metal',
    },
    {
      id: 3,
      type: 'crystal',
      x: 52,
      y: 74,
      hp: 1500,
      maxHp: 1500,
      resource: 'wood',
    },
  ],
  fragments: [
    { id: 4, x: 44, y: 51, resource: 'wood', amount: 28 },
    { id: 5, x: 48, y: 49, resource: 'metal', amount: 35 },
    { id: 6, x: 58, y: 58, resource: 'credits', amount: 26 },
  ],
  projectiles: [],
  damageTexts: [],
  quest: QUEST_CHAIN[0],
  sectorProgress: 42,
  newRocketBuilt: false,
  weaponAchievement: undefined,
  nextId: 7,
};
